### PR TITLE
Fix minor typo in motivation document

### PR DESCRIPTION
**Pull request by hazelnusse**

### CODE REVIEW

**Comment by hazelnusse** [comment]
@ned14 I'm going through the documentation to learn how to use Outcome and as I find typos I'm adding them to this pull request. Do you have any contribution guidelines I should be following? Feel free to accept this pull request as is or copy-pasta it into your own documentation scrub that I'm sure you are (or will be) working on prior to boost acceptance.

**Comment by ned14** [comment]
Firstly thanks for taking the time to submit the fixes. Some of these may break the docs build, as the api shortcode matcher is extremely stupid. So these will need a manual merge. I'll try to find time to do it tomorrow evening.

**Comment by hazelnusse** [comment]
No problem, thanks for writing this library. I'll keep updating as I get further along the documentation.

**Comment by ned14** [comment]
Merged. Thanks once again!

**Pull request merged**
