### PR TITLE
Fix BOOST_OUTCOME_NODISCARD preprocessor logic

### PR DESCRIPTION
**Pull request by hazelnusse**

### CODE REVIEW

**Comment by hazelnusse** [comment]
@ned14 is `develop` the correct target branch?

**Comment by hazelnusse** [comment]
@ned14 radio check, over?

**Comment by ned14** [comment]
Sorry, I'm currently blocked by paper writing for the WG21 mailing deadline end of this month. All free time is going on paper writing. `develop` would be the correct branch, yes. I think you'll be very likely to see progress on clearing bug backlog start of October.

**Comment by ned14** [comment]
Fixed!

**Pull request closed without merging**
